<?php
add_action( 'acf/include_fields', function() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    acf_add_local_field_group( array(
        'key' => 'group_67eaed0debeef',
        'title' => 'À propos de moi',
        'fields' => array(
            array(
                'key' => 'field_67ec0ea535dce',
                'label' => 'À propos',
                'name' => 'about',
                'aria-label' => '',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    'layout_67ec0ebf109e1' => array(
                        'key' => 'layout_67ec0ebf109e1',
                        'name' => 'about_me',
                        'label' => 'about_me',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67ec0ed735dcf',
                                'label' => 'Image',
                                'name' => 'about_me_img',
                                'aria-label' => '',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'id',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                                'preview_size' => 'medium',
                            ),
                            array(
                                'key' => 'field_67ec0f5935dd0',
                                'label' => 'Nom',
                                'name' => 'about_me_lastname',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_68122d4832266',
                                'label' => 'Prénom',
                                'name' => 'about_me_firstname',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_67ec0f6535dd1',
                                'label' => 'JOB',
                                'name' => 'about_me_job',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_67ec0f8635dd2',
                                'label' => 'Presentation',
                                'name' => 'about_me_presentation',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_67ec1018a310e' => array(
                        'key' => 'layout_67ec1018a310e',
                        'name' => 'about_skill',
                        'label' => 'about_skill',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67ec158b17333',
                                'label' => 'Compétences titre',
                                'name' => 'about_skill_titre',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_67ec1054196e7',
                                'label' => 'Les compétences',
                                'name' => 'skills',
                                'aria-label' => '',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'table',
                                'min' => 0,
                                'max' => 0,
                                'collapsed' => '',
                                'button_label' => 'Ajouter un élément',
                                'rows_per_page' => 20,
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_67ec114bb19b7',
                                        'label' => 'Nom de la compétence',
                                        'name' => 'skill_name',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'parent_repeater' => 'field_67ec1054196e7',
                                    ),
                                    array(
                                        'key' => 'field_67ec11b7b19b8',
                                        'label' => 'Niveau de compétence',
                                        'name' => 'skill_level',
                                        'aria-label' => '',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            0 => '0 étoile',
                                            1 => '1 étoile',
                                            2 => '2 étoiles',
                                            3 => '3 étoiles',
                                            4 => '4 étoiles',
                                            5 => '5 étoiles',
                                        ),
                                        'default_value' => false,
                                        'return_format' => 'value',
                                        'multiple' => 0,
                                        'allow_null' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'placeholder' => '',
                                        'parent_repeater' => 'field_67ec1054196e7',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_67ec123b7e503' => array(
                        'key' => 'layout_67ec123b7e503',
                        'name' => 'about_asset',
                        'label' => 'about_asset',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67ec12607e505',
                                'label' => 'Atouts titre',
                                'name' => 'about_asset_title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_67ec128c7e506',
                                'label' => 'Mes Atouts',
                                'name' => 'assets',
                                'aria-label' => '',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'table',
                                'min' => 0,
                                'max' => 0,
                                'collapsed' => '',
                                'button_label' => 'Ajouter un élément',
                                'rows_per_page' => 20,
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_67ec12b47e507',
                                        'label' => 'Image de l\'atout',
                                        'name' => 'about_asset_img',
                                        'aria-label' => '',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'id',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                        'preview_size' => 'medium',
                                        'parent_repeater' => 'field_67ec128c7e506',
                                    ),
                                    array(
                                        'key' => 'field_67ec12d67e508',
                                        'label' => 'Texte de l\'atout',
                                        'name' => 'about_asset_content',
                                        'aria-label' => '',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'rows' => '',
                                        'placeholder' => '',
                                        'new_lines' => '',
                                        'parent_repeater' => 'field_67ec128c7e506',
                                    ),
                                    array(
                                        'key' => 'field_67ee5a663f1e7',
                                        'label' => 'Titre',
                                        'name' => 'about_asset_article_title',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'parent_repeater' => 'field_67ec128c7e506',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_67ec133c1ae29' => array(
                        'key' => 'layout_67ec133c1ae29',
                        'name' => 'contact_redirect',
                        'label' => 'contact_redirect',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67ec134e89ab5',
                                'label' => 'Bouton lien',
                                'name' => 'contact_redirect_button',
                                'aria-label' => '',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                            ),
                            array(
                                'key' => 'field_67ec13fd89ab6',
                                'label' => 'Titre du boutton',
                                'name' => 'contact_redirect_title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_67ec14612c87f' => array(
                        'key' => 'layout_67ec14612c87f',
                        'name' => 'project_redirect',
                        'label' => 'project_redirect',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67ec14612c880',
                                'label' => 'Bouton lien',
                                'name' => 'project_redirect_button',
                                'aria-label' => '',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                            ),
                            array(
                                'key' => 'field_67ec14612c881',
                                'label' => 'Titre du boutton',
                                'name' => 'project_redirect_title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'min' => '',
                'max' => '',
                'button_label' => 'Ajouter un élément',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '22',
                ),
            ),
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '229',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );

    acf_add_local_field_group( array(
        'key' => 'group_67e927bc5f82d',
        'title' => 'Accueil',
        'fields' => array(
            array(
                'key' => 'field_67e9305a2bcbe',
                'label' => 'Présentation',
                'name' => 'presentation',
                'aria-label' => '',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    'layout_67e93303e7564' => array(
                        'key' => 'layout_67e93303e7564',
                        'name' => 'presentation_me',
                        'label' => 'presentation_me',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67e9428746446',
                                'label' => 'Citation',
                                'name' => 'presentation_title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_67e942a246448',
                                'label' => 'Profession',
                                'name' => 'presentation_profession',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'min' => '',
                'max' => '',
                'button_label' => 'Ajouter un élément',
            ),
            array(
                'key' => 'field_67e977d1b49c1',
                'label' => 'Découverte',
                'name' => 'discover',
                'aria-label' => '',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    'layout_67e978e8b4b38' => array(
                        'key' => 'layout_67e978e8b4b38',
                        'name' => 'discover_content',
                        'label' => 'discover_content',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67e9794617dc7',
                                'label' => 'Titre h2',
                                'name' => 'discover_title_h2',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_67e9796a17dc8',
                                'label' => 'Redirection vers "Qui suis-je"',
                                'name' => 'discover_content',
                                'aria-label' => '',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_67e979bd9f8d5' => array(
                        'key' => 'layout_67e979bd9f8d5',
                        'name' => 'discover_project',
                        'label' => 'discover_project',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67e979d99f8d7',
                                'label' => 'titre h3',
                                'name' => 'discover_title_h3',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_67e979f99f8d8',
                                'label' => 'Image du Projet',
                                'name' => 'discover_img',
                                'aria-label' => '',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                                'preview_size' => 'medium',
                            ),
                            array(
                                'key' => 'field_67e97a279f8d9',
                                'label' => 'link',
                                'name' => 'discover_link',
                                'aria-label' => '',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_67e97bb8328ff' => array(
                        'key' => 'layout_67e97bb8328ff',
                        'name' => 'discover_project_2',
                        'label' => 'discover_project_2',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67e97bb832900',
                                'label' => 'titre h3',
                                'name' => 'discover_title_h3',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_67e97bb832901',
                                'label' => 'Image du Projet',
                                'name' => 'discover_img',
                                'aria-label' => '',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                                'preview_size' => 'medium',
                            ),
                            array(
                                'key' => 'field_67e97bb832902',
                                'label' => 'lien',
                                'name' => 'discover_link',
                                'aria-label' => '',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_6826faa3b0fd2' => array(
                        'key' => 'layout_6826faa3b0fd2',
                        'name' => 'discover_project_3',
                        'label' => 'discover_project_3',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_6826faa3b0fd3',
                                'label' => 'titre h3',
                                'name' => 'discover_title_h3',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_6826faa3b0fd4',
                                'label' => 'Image du Projet',
                                'name' => 'discover_img',
                                'aria-label' => '',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                                'preview_size' => 'medium',
                            ),
                            array(
                                'key' => 'field_6826faa3b0fd5',
                                'label' => 'lien',
                                'name' => 'discover_link',
                                'aria-label' => '',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'min' => '',
                'max' => '',
                'button_label' => 'Ajouter un élément',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_type',
                    'operator' => '==',
                    'value' => 'front_page',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );

    acf_add_local_field_group( array(
        'key' => 'group_67fd308d3eb81',
        'title' => 'Contact',
        'fields' => array(
            array(
                'key' => 'field_67fd308d46755',
                'label' => 'Titre information',
                'name' => 'form_information_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_67fd30ea46756',
                'label' => 'Téléphone',
                'name' => 'form_information_phone',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_67fd311946757',
                'label' => 'Email',
                'name' => 'form_information_mail',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '39',
                ),
            ),
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '225',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );

    acf_add_local_field_group( array(
        'key' => 'group_67ee546bb1dd1',
        'title' => 'Mes projets',
        'fields' => array(
            array(
                'key' => 'field_67ee546cee6aa',
                'label' => 'Page projets',
                'name' => 'project',
                'aria-label' => '',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    'layout_68010d1653c81' => array(
                        'key' => 'layout_68010d1653c81',
                        'name' => 'project_title',
                        'label' => 'Titres',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_68010d2953c83',
                                'label' => 'Titre',
                                'name' => 'title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_68010e3c53c84',
                                'label' => 'Titre filtre',
                                'name' => 'title_filter',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_67ee58becf6fa' => array(
                        'key' => 'layout_67ee58becf6fa',
                        'name' => 'presentation_redirect',
                        'label' => 'presentation_redirect',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67ee58d6cf6fc',
                                'label' => 'Titre',
                                'name' => 'presentation_redirect_title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_67ee58e5cf6fd',
                                'label' => 'Lien redirection',
                                'name' => 'presentation_redirect_link',
                                'aria-label' => '',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'min' => '',
                'max' => '',
                'button_label' => 'Ajouter un élément',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '165',
                ),
            ),
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '227',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );

    acf_add_local_field_group( array(
        'key' => 'group_67ee84d26a548',
        'title' => 'Projet',
        'fields' => array(
            array(
                'key' => 'field_67ee84d2d8e0d',
                'label' => 'Projet',
                'name' => 'projet',
                'aria-label' => '',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    'layout_67ee86c2dad41' => array(
                        'key' => 'layout_67ee86c2dad41',
                        'name' => 'single_projet',
                        'label' => 'single_projet',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67ee88840e263',
                                'label' => 'Titre du projet',
                                'name' => 'single_projet_title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_67ee88960e264',
                                'label' => 'Image du projet',
                                'name' => 'single_projet_img',
                                'aria-label' => '',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                                'preview_size' => 'medium',
                            ),
                            array(
                                'key' => 'field_67ee88c50e265',
                                'label' => 'Contenu du projet',
                                'name' => 'single_projet_content',
                                'aria-label' => '',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'table',
                                'min' => 0,
                                'max' => 0,
                                'collapsed' => '',
                                'button_label' => 'Ajouter un élément',
                                'rows_per_page' => 20,
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_67ee88ed0e266',
                                        'label' => 'Titre',
                                        'name' => 'single_projet_title',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'parent_repeater' => 'field_67ee88c50e265',
                                    ),
                                    array(
                                        'key' => 'field_67ee89230e267',
                                        'label' => 'Texte',
                                        'name' => 'single_projet_texte',
                                        'aria-label' => '',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'rows' => '',
                                        'placeholder' => '',
                                        'new_lines' => '',
                                        'parent_repeater' => 'field_67ee88c50e265',
                                    ),
                                    array(
                                        'key' => 'field_68024867bfd78',
                                        'label' => 'Galerie ou Photo',
                                        'name' => 'single_project_choice',
                                        'aria-label' => '',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                        'parent_repeater' => 'field_67ee88c50e265',
                                    ),
                                    array(
                                        'key' => 'field_67ee89f858e6c',
                                        'label' => 'Galerie',
                                        'name' => 'single_project_fig',
                                        'aria-label' => '',
                                        'type' => 'gallery',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => 'field_68024867bfd78',
                                                    'operator' => '!=',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'library' => 'all',
                                        'min' => '',
                                        'max' => '',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                        'insert' => 'append',
                                        'preview_size' => 'medium',
                                        'parent_repeater' => 'field_67ee88c50e265',
                                    ),
                                    array(
                                        'key' => 'field_680248fcbfd79',
                                        'label' => 'Unique photo',
                                        'name' => 'single_project_img',
                                        'aria-label' => '',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => 'field_68024867bfd78',
                                                    'operator' => '!=',
                                                    'value' => 'photo',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                        'preview_size' => 'medium',
                                        'parent_repeater' => 'field_67ee88c50e265',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_67ee8ace7dc6a' => array(
                        'key' => 'layout_67ee8ace7dc6a',
                        'name' => 'contact_redirect',
                        'label' => 'contact_redirect',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_67ee8adc7dc6c',
                                'label' => 'bouton_lien',
                                'name' => 'contact_redirect_button',
                                'aria-label' => '',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                            ),
                            array(
                                'key' => 'field_67ee8af87dc6d',
                                'label' => 'Titre du bouton',
                                'name' => 'contact_redirect_title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'min' => '',
                'max' => '',
                'button_label' => 'Ajouter un élément',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'project',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );
} );

